server:
  port: 8022
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mysql://localhost:3306/business?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: business
    password: 123456
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8

mybatis:
  type-aliases-package: com.zheng.business
  mapper-locations: classpath:dao/*.xml


